export const iconsList = [
    { label: "Configurações", value: "pi pi-cog" },
    { label: "Eraser", value: "pi pi-eraser" },
    { label: "Stopwatch", value: "pi pi-stopwatch" },
    { label: "Verified", value: "pi pi-verified" },
    { label: "Delete Left", value: "pi pi-delete-left" },
    { label: "Hourglass", value: "pi pi-hourglass" },
    { label: "Truck", value: "pi pi-truck" },
    { label: "Wrench", value: "pi pi-wrench" },
    { label: "Microphone", value: "pi pi-microphone" },
    { label: "Megaphone", value: "pi pi-megaphone" },
    { label: "Arrow Right Arrow Left", value: "pi pi-arrow-right-arrow-left" },
    { label: "Bitcoin", value: "pi pi-bitcoin" },
    { label: "File Edit", value: "pi pi-file-edit" },
    { label: "Language", value: "pi pi-language" },
    { label: "File Export", value: "pi pi-file-export" },
    { label: "File Import", value: "pi pi-file-import" },
    { label: "File Word", value: "pi pi-file-word" },
    { label: "Gift", value: "pi pi-gift" },
    { label: "Cart Plus", value: "pi pi-cart-plus" },
    { label: "Thumbs Down Fill", value: "pi pi-thumbs-down-fill" },
    { label: "Thumbs Up Fill", value: "pi pi-thumbs-up-fill" },
    { label: "Arrows Alt", value: "pi pi-arrows-alt" },
    { label: "Calculator", value: "pi pi-calculator" },
    { label: "Spinner", value: "pi pi-spinner" },
    { label: "Home", value: "pi pi-home" },
];

